name: "Build Pipeline"

on:
    push:
        branches:
            - master

jobs:
    package:
        name: Package Docker
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                name: Checkout Code
            -   name: Login to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    file: ./Dockerfile
                    tags: |
                        ghcr.io/lucasreiners/custom-caddy-proxy:latest